import Head from "next/head";
import { type NextPage } from "next";
import systemConfig from "../system.json";

const Home: NextPage = () => {
    // Mock image based on keyword using LoremFlickr (more reliable than source.unsplash currently) or Placehold.co for safety
    // Using a tech-agnostic reliable placeholder service if needed, but let's try a dynamic directed url
    // Note: {{IMAGE_KEYWORD}} will be replaced by the CLI.
    const bgImage = "https://loremflickr.com/1920/1080/{{IMAGE_KEYWORD}},business/all";

    return (
        <>
            <Head>
                <title>{{ SYSTEM_NAME }}</title>
                <meta name="description" content="{{ DESCRIPTION }}" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* 
        Dynamic Theme injection 
        In a real app, this would be handled by Tailwind config, but we can do inline styles for the generated demo.
      */}
            <main className="flex min-h-screen flex-col items-center justify-center relative overflow-hidden">

                {/* Background Image Overlay */}
                <div
                    className="absolute inset-0 z-0 opacity-20 bg-cover bg-center"
                    style={{ backgroundImage: `url(${bgImage})` }}
                />
                <div className="absolute inset-0 z-0 bg-gradient-to-b from-slate-900 to-slate-950 opacity-90" />

                <div className="container z-10 flex flex-col items-center justify-center gap-12 px-4 py-16 text-white">
                    <div className="text-center space-y-4">
                        <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem] drop-shadow-xl">
                            <span className="block text-2xl font-medium opacity-80 mb-2">Welcome to your</span>
                            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">
                                {{ SYSTEM_NAME }}
                            </span>
                        </h1>
                        <p className="text-xl text-slate-300 max-w-2xl mx-auto">
                            {{ DESCRIPTION }}
                        </p>
                    </div>

                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 md:gap-8 w-full max-w-4xl">
                        {/* Dynamic Role Login Cards */}
                        {systemConfig.roles.map((role: string) => (
                            <div key={role} className="flex flex-col gap-4 rounded-xl bg-white/5 p-6 border border-white/10 hover:bg-white/10 transition-all hover:scale-105 cursor-pointer backdrop-blur-sm">
                                <div className="h-12 w-12 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 text-2xl font-bold">
                                    {role.charAt(0).toUpperCase()}
                                </div>
                                <div>
                                    <h3 className="text-xl font-bold">{role} Portal →</h3>
                                    <div className="text-sm text-slate-400">
                                        Log in as {role} to access dashboard.
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>

                    <div className="mt-12 p-4 rounded-lg bg-orange-500/10 border border-orange-500/20 text-orange-200 text-sm max-w-lg text-center">
                        <span className="font-bold">⚠️ Generator Mode:</span> This system was auto-generated by Core Frameworks.
                        <br /> Customize logic in <code>src/server/api/routers</code>.
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;
