export const metadata = {
    title: "Project Structure - ArchillesDC Docs",
    description: "Complete reference of all files generated by ArchillesDC",
};

export default function ProjectStructurePage() {
    return (
        <article className="max-w-none prose prose-invert">
            <h1 className="text-4xl font-bold mb-4 text-white">Project Structure</h1>
            <p className="text-lg text-gray-400 mb-8 leading-relaxed">
                Complete reference of all files generated by ArchillesDC.
            </p>

            <h2 className="text-2xl font-bold mt-12 mb-6 text-white">Root Configuration Files</h2>

            <div className="space-y-6">
                <div>
                    <h3 className="text-lg font-semibold text-white mb-2">package.json</h3>
                    <p className="text-gray-400 text-sm mb-2">Project configuration and dependencies.</p>
                </div>

                <div>
                    <h3 className="text-lg font-semibold text-white mb-2">tsconfig.json</h3>
                    <div className="bg-[#12121a] rounded-lg border border-white/10 p-4 overflow-x-auto">
                        <pre className="text-sm font-mono text-gray-300">{`{
  "compilerOptions": {
    "target": "es2022",
    "lib": ["dom", "dom.iterable", "ES2022"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`}</pre>
                    </div>
                </div>

                <div>
                    <h3 className="text-lg font-semibold text-white mb-2">.env.example</h3>
                    <div className="bg-[#12121a] rounded-lg border border-white/10 p-4 overflow-x-auto">
                        <pre className="text-sm font-mono text-gray-300">{`# Database
DATABASE_URL="file:./db.sqlite"

# NextAuth
AUTH_SECRET=""
AUTH_URL="http://localhost:3000"

# OAuth (optional)
AUTH_DISCORD_ID=""
AUTH_DISCORD_SECRET=""`}</pre>
                    </div>
                </div>
            </div>

            <h2 className="text-2xl font-bold mt-12 mb-6 text-white">Prisma Files</h2>
            <p className="text-gray-400 mb-4">Location: <code className="bg-white/10 px-1 py-0.5 rounded text-white text-sm">prisma/</code></p>

            <div className="space-y-6">
                <div>
                    <h3 className="text-lg font-semibold text-white mb-2">schema.prisma</h3>
                    <p className="text-gray-400 text-sm mb-2">Database schema definition.</p>
                    <div className="bg-[#12121a] rounded-lg border border-white/10 p-4 overflow-x-auto">
                        <pre className="text-sm font-mono text-gray-300">{`generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(cuid())
  email String @unique
  name  String?
  role  String @default("user")
  // ...
}`}</pre>
                    </div>
                </div>

                <div>
                    <h3 className="text-lg font-semibold text-white mb-2">seed.ts</h3>
                    <p className="text-gray-400 text-sm mb-2">Database seeding script.</p>
                </div>
            </div>

            <h2 className="text-2xl font-bold mt-12 mb-6 text-white">Source Files</h2>
            <p className="text-gray-400 mb-4">Location: <code className="bg-white/10 px-1 py-0.5 rounded text-white text-sm">src/</code></p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
                <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                    <code className="text-violet-400 font-mono text-sm block mb-2">env.js</code>
                    <p className="text-gray-400 text-sm">Environment validation with T3 Env</p>
                </div>
                <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                    <code className="text-violet-400 font-mono text-sm block mb-2">server/db.ts</code>
                    <p className="text-gray-400 text-sm">Prisma client instance (singleton)</p>
                </div>
            </div>

            <h3 className="text-xl font-semibold mt-8 mb-4 text-white">App Directory</h3>
            <p className="text-gray-400 mb-4">Location: <code className="bg-white/10 px-1 py-0.5 rounded text-white text-sm">src/app/</code></p>
            <ul className="list-disc list-inside space-y-2 text-gray-300 mb-8 ml-4">
                <li><code className="text-white">layout.tsx</code> - Root layout with providers</li>
                <li><code className="text-white">page.tsx</code> - Home page</li>
                <li><code className="text-white">error.tsx</code> - Global error boundary</li>
                <li><code className="text-white">not-found.tsx</code> - 404 page</li>
                <li><code className="text-white">loading.tsx</code> - Global loading state</li>
            </ul>

            <h3 className="text-xl font-semibold mt-8 mb-4 text-white">Auth Files</h3>
            <p className="text-gray-400 mb-4">Location: <code className="bg-white/10 px-1 py-0.5 rounded text-white text-sm">src/server/auth/</code></p>
            <ul className="list-disc list-inside space-y-2 text-gray-300 mb-8 ml-4">
                <li><code className="text-white">config.ts</code> - NextAuth configuration</li>
                <li><code className="text-white">index.ts</code> - Auth helpers (auth, getCurrentUser)</li>
                <li><code className="text-white">actions.ts</code> - Server actions (signIn, signOut)</li>
            </ul>

            <h3 className="text-xl font-semibold mt-8 mb-4 text-white">tRPC Files</h3>
            <p className="text-gray-400 mb-4">Location: <code className="bg-white/10 px-1 py-0.5 rounded text-white text-sm">src/server/api/</code></p>
            <ul className="list-disc list-inside space-y-2 text-gray-300 mb-8 ml-4">
                <li><code className="text-white">trpc.ts</code> - tRPC initialization & procedures</li>
                <li><code className="text-white">root.ts</code> - App router & type definition</li>
                <li><code className="text-white">routers/</code> - Individual API routers</li>
            </ul>

            <h2 className="text-2xl font-bold mt-12 mb-6 text-white">Component Files</h2>
            <p className="text-gray-400 mb-4">Location: <code className="bg-white/10 px-1 py-0.5 rounded text-white text-sm">src/components/</code></p>

            <h3 className="text-lg font-semibold mt-6 mb-2 text-white">UI Components</h3>
            <div className="overflow-x-auto mb-8 rounded-lg border border-white/10">
                <table className="w-full text-left text-sm">
                    <thead className="bg-white/5 text-gray-400 border-b border-white/10">
                        <tr><th className="px-4 py-3 font-medium">File</th><th className="px-4 py-3 font-medium">Component</th><th className="px-4 py-3 font-medium">Description</th></tr>
                    </thead>
                    <tbody className="divide-y divide-white/10 text-gray-300">
                        <tr><td className="px-4 py-3 font-mono text-violet-400 text-xs">button.tsx</td><td className="px-4 py-3">Button</td><td className="px-4 py-3">Button with variants</td></tr>
                        <tr><td className="px-4 py-3 font-mono text-violet-400 text-xs">input.tsx</td><td className="px-4 py-3">Input</td><td className="px-4 py-3">Text input with label/error</td></tr>
                        <tr><td className="px-4 py-3 font-mono text-violet-400 text-xs">card.tsx</td><td className="px-4 py-3">Card</td><td className="px-4 py-3">Card container</td></tr>
                        <tr><td className="px-4 py-3 font-mono text-violet-400 text-xs">toast.tsx</td><td className="px-4 py-3">ToastProvider</td><td className="px-4 py-3">Toast notifications</td></tr>
                        <tr><td className="px-4 py-3 font-mono text-violet-400 text-xs">modal.tsx</td><td className="px-4 py-3">Modal</td><td className="px-4 py-3">Modal dialog</td></tr>
                    </tbody>
                </table>
            </div>

            <h2 className="text-2xl font-bold mt-12 mb-6 text-white">Utility Files</h2>
            <ul className="list-disc list-inside space-y-2 text-gray-300 mb-8 ml-4">
                <li><code className="text-white">src/utils/cn.ts</code> - Tailwind class merger</li>
                <li><code className="text-white">src/utils/formatters.ts</code> - Data formatters</li>
                <li><code className="text-white">src/lib/logger.ts</code> - Structured logging</li>
                <li><code className="text-white">src/lib/crud-helper.ts</code> - tRPC CRUD helpers</li>
            </ul>

            <h2 className="text-2xl font-bold mt-12 mb-6 text-white">Global Styles</h2>
            <p className="text-gray-400 mb-4">Location: <code className="bg-white/10 px-1 py-0.5 rounded text-white text-sm">src/styles/globals.css</code></p>
            <div className="bg-[#12121a] rounded-lg border border-white/10 p-4 mb-4 overflow-x-auto">
                <pre className="text-sm font-mono text-gray-300">{`@import "tailwindcss";

@theme {
  --color-background: #0a0a0f;
  --color-surface: #12121a;
  --color-primary: #7c3aed;
}

body {
  font-family: var(--font-sans);
  background: var(--color-background);
}`}</pre>
            </div>
        </article>
    );
}
